@echo off 
echo *********************顺易通前端工程WEBAPP(H5)打包开始.......... 
echo 正在清除旧编译文件，请稍等...... 
del /f /s /q .\build\webapp\*.*
rd /q /s .\build\webapp\
md .\build\webapp\
del /f /s /q .\build\qrcode\*.*
rd /q /s .\build\qrcode\
md .\build\qrcode\
del /f /s /q .\output\*.*
del .\webapp(H5).zip
echo 清除完成！编译开始....
echo 初始化加载文件模块开始....
call .\pack\init.bat 
echo 初始化加载文件模块结束....
echo 编译开始....
call .\pack\pack.bat 
call .\pack\pack_scan.bat 
call .\pack\move.bat 
call .\pack\move_scan.bat 
echo 编译结束....
echo 打包开始....压缩....
call .\pack\zip.bat 
echo *********************顺易通前端工程WEBAPP(H5)打包结束.......... 
echo. & pause 